# Generated by Django 5.2 on 2025-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('time', models.DateField(verbose_name='time')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Temperature')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Min Temperature')),
                ('weather_code', models.IntegerField(verbose_name='Weather Code')),
                ('weather_description', models.CharField(max_length=100, verbose_name='Weather_Description')),
            ],
            options={
                'db_table': 'predict_weather',
                'ordering': ['province', 'time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Temperature')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Min Temperature')),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precipitation')),
                ('windspeed_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Windspeed')),
                ('uv_index_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max UV Index')),
                ('sunshine_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sunshine Hours')),
                ('sundown_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sundown Hours')),
                ('weather_code', models.IntegerField(verbose_name='Weather Code')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humidity')),
                ('feel_like', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Feels Like')),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['province', 'time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
